apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app:
          db-service
    spec:
      containers:
        - name: db-service
          image: todo99.azurecr.io/db-service:v0.0.6
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DSN
              value: "host=postgres-service port=5432 user=postgres password=password dbname=todo sslmode=disable"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-auth

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    name: db-service
  ports:
    - protocol: TCP
      name: main-port
      port: 5001
      targetPort: 5001



